language: android
android:
  components:
  - platform-tools
  - extra
  - android-21
  - build-tools-21.1.2
script:
- gradle clean build
notifications:
  slack:
    secure: ZHXQ3GQs7w5Svdweg3ZIzGxQo3DvSZlWWqR1Uyl6AiIUKLqjtM6KqriJDToja4lQu/DqFZb5OhBVGr08zutwcyQoW5AmRigSHFjEdb5nXs7YgLglPqxu3TAdXwjBN88otx0FNDeNbJOaN8EeNfyxTHtiUkSLafuobvgeTFUCWpA=
  email:
    recipients:
    - jak@microsoft.com
    on_success: never
    on_failure: always
